jq_uploadDB: &jq_uploadDB
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tmello
  password: 
  host: localhost

development:
  <<: *jq_uploadDB
  database: jq_upload_development

test:
  <<: *jq_uploadDB
  database: jq_upload_test

production:
  <<: *jq_uploadDB
  database: jq_upload_production

